[New Feature] Integrate "Winget Releaser"
clash-verge-rev/clash-verge-rev pull request #1326
Opened 2024-07-04 06:45 UTC by Dragon1573

- Resolve #1322

2024-07-04 11:16 UTC, MystiPanda requested changes

2024-07-04 11:16 UTC, MystiPanda commented on .github/workflows/release.yml
> +          identifer: MystiPanda.ClashVerge
ClashVergeRev.ClashVergeRev

2024-07-04 11:17 UTC, MystiPanda commented
应该放一个单独的job并添加need依赖

2024-07-04 14:11 UTC, Dragon1573 commented on .github/workflows/release.yml
> +          identifer: MystiPanda.ClashVerge
当前这个 `MystiPanda.ClashVerge` 是已经在库中的，_WinGet Releaser_ 需要基于已经存在的旧版本 Manifests 去生成新版本。

如果需要，我可以同步开启 Issue 和 PR 完成相关改名事项。

2024-07-04 16:07 UTC, Dragon1573 commented
> [!NOTE]
>
> 当前 PR 需要暂时转入「草稿」状态，以等待上游仓库完成 `PackageIdentifier` 的全部更改。
>
> 更改完成后方可重启 PR 。

2024-07-07 07:10 UTC, Dragon1573 commented
当前，版本 `v1.6.2` 与 `v1.6.6` 已完成标识符切换，`v1.6.4` 与 `v1.7.2` 等待入库手动合并中。

此 PR 可以重新开放等待审核。

2024-07-07 12:41 UTC, MystiPanda approved these changes

2024-07-07 12:42 UTC, merged