feat: 新增流量统计模块
clash-verge-rev/clash-verge-rev pull request #1501
Opened 2024-07-30 10:05 UTC by TanxiangCode

增加了一个流量统计的功能

1. 缺少一个彩色图标，大佬画一下，我不会。。
2. 仅测试了win，其他的我没有。。

2024-08-02 05:43 UTC, SukkaW requested changes

2024-08-02 05:43 UTC, SukkaW commented on src/services/traffic-worker.ts
> +self.onmessage = async (event) => {
Use `addEventListener`.

2024-08-02 05:43 UTC, SukkaW commented on src/services/traffic-worker.ts
> +  const { type, data } = event.data;
Missing typescript type declarations.

2024-08-02 05:43 UTC, SukkaW commented on src/services/traffic-worker.ts
> +})();
```suggestion
startBackgroundTask();
```

Also missing dispose function.

2024-08-02 05:43 UTC, SukkaW commented on src/components/layout/layout-traffic.tsx
> +console.log(new URL("@/services/traffic-worker.ts", import.meta.url));
Remove `console.log`.

2024-08-02 05:43 UTC, SukkaW commented on src/components/layout/layout-traffic.tsx
> +};
Use `addEventListener`. Also add proper error handling.

2024-08-06 02:16 UTC, closed without merging

2024-08-06 02:16 UTC, TanxiangCode commented
This approach has an issue: when minimized to the system tray, the worker will stop, and data writing will also cease. Alternative solutions need to be considered for data writing and processing.